In [1]:
import pandas as pd
import sqlalchemy as sa
connection_string = (
    r"DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};"
    r"DBQ=C:\Users\DEVRIEND\OneDrive - VITO\Documents\git\parco-hbm\linkml\source_tables\INQUIRE\INQUIRE.mdb;"
    r"ExtendedAnsiSQL=1;"
)
connection_url = sa.engine.URL.create(
    "access+pyodbc",
    query={"odbc_connect": connection_string}
)
engine = sa.create_engine(connection_url)

In [5]:
SQL_qryField = """
SELECT metaFields.PageId, metaPages.Name, metaFields.TabIndex, metaFields.Name, metaFields.PromptText, metaFields.IsRequired, metaFields.MaxLength, metaFields.Lower, metaFields.Upper, metaFields.SourceTableName, metaFields.CodeColumnName, metaFields.TextColumnName, metaFieldTypes.Name, metaFieldTypes.IsDropDown, metaDataTypes.Name, metaFields.Pattern, metaFields.List
FROM metaPages RIGHT JOIN ((metaDataTypes RIGHT JOIN metaFieldTypes ON metaDataTypes.DataTypeId = metaFieldTypes.DataTypeId) RIGHT JOIN metaFields ON metaFieldTypes.FieldTypeId = metaFields.FieldTypeId) ON metaPages.PageId = metaFields.PageId
ORDER BY metaFields.PageId, metaFields.TabIndex;
"""
df = pd.read_sql_query("SELECT * FROM qryFields", engine)

In [3]:
table_names = ["codebeh_choice1", "codebeh_choices1", "codebreast_feeding1", "codecare_products_child1", "codecareproducts_ecolabel_child1", "codeconcern_airquality1", "codeconsciousness_ladder1", "codecycling_walking_child1", "codedd_asthma_allergy_family1", "codedoyouhaveddasthma1", "codeelectronics_child1", "codeeyeproblem1", "codejudged_airquality1", "codemotorizedvehicle_child1", "codemouthing_behaviour1", "coden71educationrespondent1", "coden72educationpartner1", "codenoseproblem1", "codepersonalcareproducts1", "codeplay_floor_child1", "codesex_child1", "codesmoking_room1", "codespecify_place1", "codestagnantbadair1", "codetemperature_reg1", "codetotal_income_category1"]
code_dict = {}
for tn in table_names:
    df = pd.read_sql_table(tn, engine)
    if len(df.columns) != 1:
        print(f"error in {tn}")
    code_dict[tn] = {
        "name": str(df.columns[0]),
        "values": list(df[df.columns[0]].values)
    }

In [25]:
import yaml

with open('field_codes.yml', 'w') as outfile:
    yaml.dump(code_dict, outfile, default_flow_style=False)

In [6]:
df

,PageId,Name,TabIndex,PromptText,IsRequired,MaxLength,Lower,Upper,SourceTableName,CodeColumnName,TextColumnName,IsDropDown,Pattern,List
0,NaN,Number,NaN,None,False,NaN,None,None,None,None,None,False,None,None
1,NaN,Number,NaN,None,False,NaN,None,None,None,None,None,False,None,None
2,NaN,Text,NaN,None,False,NaN,None,None,None,None,None,False,None,None
3,1.0,Text,1.0,"Participant ID (e.g., CZ_PS_JF)",True,0.0,None,None,None,None,None,True,None,None
4,1.0,Date,2.0,Today's date (as filled by participant on ques...,True,NaN,,2023-05-16,None,None,None,False,YYYY-MM-DD,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,8.0,Unknown,11.0,Regulate temperature (heat / cool),False,NaN,None,None,codetemperature_reg1,temperature_reg,temperature_reg,True,None,None
193,8.0,Unknown,12.0,Regulate ventilation,False,NaN,None,None,codetemperature_reg1,temperature_reg,temperature_reg,True,None,None
194,8.0,Unknown,13.0,Open window,False,NaN,None,None,codetemperature_reg1,temperature_reg,temperature_reg,True,None,None
195,8.0,Unknown,14.0,Use products with an EU Ecolabel to clean the ...,False,NaN,None,None,codetemperature_reg1,temperature_reg,temperature_reg,True,None,None
196,8.0,Unknown,15.0,Use only natural non-toxic products to clean t...,False,NaN,None,None,codetemperature_reg1,temperature_reg,temperature_reg,True,None,None